export const APP_TITLE = 'StadiumPulse AI'
export const APP_DESCRIPTION = 'GenAI operations copilot for FIFA World Cup 2026 stadiums'
export const AI_WELCOME_MESSAGE = 'Welcome to StadiumPulse! How can I help you today?'
export const AI_ERROR_MESSAGE = 'Sorry, I am having trouble connecting right now.'
export const OFFLINE_MESSAGE = 'Assistant is currently offline due to missing configuration.'
export const RATE_LIMIT_MESSAGE = "I'm processing too many requests. Please wait a moment."
export const INVALID_QUESTION_MESSAGE = 'Please ask a valid question.'
export const GENERIC_ERROR_MESSAGE = 'The stadium assistant encountered an error while processing your request. Please try again later.'
export const GEMINI_MODEL = 'gemini-1.5-flash'
export const RATE_LIMIT_MS = 800
